-- https://school.programmers.co.kr/learn/courses/30/lessons/131117

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT) * P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID -- SUM()나오면 그룹화 생각하기
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC