-- https://school.programmers.co.kr/learn/courses/30/lessons/131534

SELECT DATE_FORMAT(O.SALES_DATE, '%Y') AS YEAR
    , DATE_FORMAT(O.SALES_DATE, '%m') AS MONTH
    , COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS -- 한 아이디가 구매이력이 여러개 일수 있어서 중복제거 해주기 
    , ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO -- 소수점 2번째 자리에서 반올림 
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE U.JOINED LIKE '2021%' -- 전체 조건
GROUP BY MONTH -- 달별로 나옴
ORDER BY YEAR, MONTH