-- https://school.programmers.co.kr/learn/courses/30/lessons/151139
-- 어렵다...ㅜ

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    AND CAR_ID IN (SELECT CAR_ID
                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                  WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
                  GROUP BY CAR_ID
                  HAVING COUNT(*) >= 5
                  )
GROUP BY  MONTH(START_DATE), CAR_ID -- 월별, 자동차 id별
HAVING RECORDS > 0
ORDER BY MONTH(START_DATE), CAR_ID DESC